FROM infiniteproject/icecast:latest
LABEL maintainer="formatcomvinicio@gmail.com"

ENV ICECAST_SOURCE_PASSWORD hackme
ENV ICECAST_ADMIN_EMAIL formatcomvinicio@gmail.com
ENV ICECAST_ADMIN_USERNAME admin
ENV ICECAST_ADMIN_PASSWORD hackme

# ASIGNAR EL PUERTO A HEROKU
CMD sed -ri "s/<port>8000<\/port>/<port>$PORT<\/port>/g" /etc/icecast.xml && icecast -c /etc/icecast.xml
